name: Code review
on:
  push:
  pull_request:
jobs:
  pycodestyle:
    name: pycodestyle
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: wemake-python-styleguide
      uses: ankitvgupta/pycodestyle-action@master
      with:
        reporter: 'github-pr-review'
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
